version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd selenium-test
      - mvn clean install --projects test-framework --also-make
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - selenium-test/target/test-project-1.0-SNAPSHOT.jar
    - selenium-test/target/surefire-reports/testng-results.xml
