version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - sudo curl https://intoli.com/install-google-chrome.sh | bash
      - sudo mv /usr/bin/google-chrome-stable /usr/bin/google-chrome
      - google-chrome --version && which google-chrome
  build:
    commands:
      - echo Build started on `date`
      - cd build-project
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build-project/selenium-test/target/test-project-1.0-SNAPSHOT.jar
    - build-project/selenium-test/target/surefire-reports/testng-results.xml