version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo pre build phase started on `date`
      - curl https://intoli.com/install-google-chrome.sh | bash
  build:
    commands:
      - echo build phase started on `date`
      - cd build-project
      - mvn install
  post_build:
    commands:
      - echo build completed on `date`
artifacts:
  files:
    - build-project/selenium-test/target/test-project-1.0-SNAPSHOT.jar
    - build-project/selenium-test/target/surefire-reports/testng-results.xml