version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo pre build phase started on `date`
      - curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
      - apt-get -y update
      - apt-get -y install google-chrome-stable
      - google-chrome --version && which google-chrome
  build:
    commands:
      - echo build phase started on `date`
      - cd build-project
      - mvn install
  post_build:
    commands:
      - echo build completed on `date`
artifacts:
  files:
    - build-project/selenium-test/target/test-project-1.0-SNAPSHOT.jar
    - build-project/selenium-test/target/surefire-reports/testng-results.xml