version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo pre_build phase...
      - echo Installing Chrome
      - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google.list
      - apt-get -qq update
      - apt-get -qq install -y google-chrome-stable
      - google-chrome --version
  build:
    commands:
      - echo Build started on `date`
      - cd build-project
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build-project/selenium-test/target/test-project-1.0-SNAPSHOT.jar
    - build-project/selenium-test/target/surefire-reports/testng-results.xml